{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPNTIK4mB96m5n90RF25Fal"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [],
      "metadata": {
        "id": "Po2kqrb15cJ_"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Part A: Knowledge Representation + Rule-Based Reasoning (RBR)\n",
        "# Use case: Laptop troubleshooting assistant\n",
        "\n",
        "facts = {\n",
        "    \"power\": {\n",
        "        \"powers_on\": True,\n",
        "        \"battery_level\": 12,        # percent\n",
        "        \"is_plugged_in\": False,\n",
        "    },\n",
        "    \"thermal\": {\n",
        "        \"temperature_c\": 92,        # CPU temperature\n",
        "        \"fan_noise\": \"loud\",        # \"normal\" or \"loud\"\n",
        "    },\n",
        "    \"display\": {\n",
        "        \"screen_on\": True,\n",
        "        \"screen_flickering\": False,\n",
        "        \"storage_free_gb\": 3,       # included for the storage rule\n",
        "    },\n",
        "}\n",
        "\n",
        "def rule_no_power(facts):\n",
        "    if not facts[\"power\"][\"powers_on\"] and not facts[\"power\"][\"is_plugged_in\"]:\n",
        "        return \"Plug in the charger and check the power outlet\"\n",
        "\n",
        "def rule_low_battery(facts):\n",
        "    if facts[\"power\"][\"battery_level\"] < 20 and not facts[\"power\"][\"is_plugged_in\"]:\n",
        "        return \"Battery is low - plug in the charger\"\n",
        "\n",
        "def rule_overheating(facts):\n",
        "    if facts[\"thermal\"][\"temperature_c\"] > 85:\n",
        "        return \"Close heavy programs and place the laptop on a cooling pad\"\n",
        "\n",
        "def rule_loud_fan(facts):\n",
        "    if facts[\"thermal\"][\"fan_noise\"] == \"loud\":\n",
        "        return \"Clean the fan and air vents from dust\"\n",
        "\n",
        "def rule_flicker(facts):\n",
        "    if facts[\"display\"][\"screen_flickering\"]:\n",
        "        return \"Update the graphics/display driver\"\n",
        "\n",
        "def rule_low_storage(facts):\n",
        "    if facts[\"display\"][\"storage_free_gb\"] < 10:\n",
        "        return \"Delete unused files or run Disk Cleanup\"\n",
        "\n",
        "# The rule base (the list the inference engine will go through)\n",
        "rules = [rule_no_power, rule_low_battery, rule_overheating,\n",
        "         rule_loud_fan, rule_flicker, rule_low_storage]\n",
        "\n",
        "\n",
        "# Task 2B: Inference engine\n",
        "def inference_engine(facts, rules):\n",
        "    # Read the knowledge base, check each rule, return all inferred actions.\n",
        "    actions = []                       # working memory of conclusions\n",
        "    for rule in rules:                 # check every rule\n",
        "        result = rule(facts)           # evaluate the IF part\n",
        "        if result is not None:         # rule fired -> keep the THEN part\n",
        "            actions.append(result)\n",
        "    return actions\n",
        "\n",
        "\n",
        "# Task 2C: Display output\n",
        "if __name__ == \"__main__\":\n",
        "    print(\"Knowledge Base (Facts):\")\n",
        "    for category, items in facts.items():\n",
        "        print(f\"  [{category}]\")\n",
        "        for name, value in items.items():\n",
        "            print(f\"    {name}: {value}\")\n",
        "\n",
        "    print(\"\\nRule-Based Reasoning Actions:\")\n",
        "    inferred = inference_engine(facts, rules)\n",
        "    if inferred:\n",
        "        for action in inferred:\n",
        "            print(f\"- {action}\")\n",
        "    else:\n",
        "        print(\"- No rule matched. No action needed.\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "nmiW071i5V3P",
        "outputId": "7db6aa83-9ee9-4383-bb3f-ce05475d48b8"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Knowledge Base (Facts):\n",
            "  [power]\n",
            "    powers_on: True\n",
            "    battery_level: 12\n",
            "    is_plugged_in: False\n",
            "  [thermal]\n",
            "    temperature_c: 92\n",
            "    fan_noise: loud\n",
            "  [display]\n",
            "    screen_on: True\n",
            "    screen_flickering: False\n",
            "    storage_free_gb: 3\n",
            "\n",
            "Rule-Based Reasoning Actions:\n",
            "- Battery is low - plug in the charger\n",
            "- Close heavy programs and place the laptop on a cooling pad\n",
            "- Clean the fan and air vents from dust\n",
            "- Delete unused files or run Disk Cleanup\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "IFJVXJd51uIy",
        "outputId": "04b29607-6384-4f89-8a50-fd8c6e7c5524"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "=== Case-Based Reasoning: Laptop Troubleshooter ===\n",
            "\n",
            "Describe your laptop problem (y/n):\n",
            "  wont turn on? a\n",
            "Invalid input! Please enter 'y' or 'n'.\n",
            "  wont turn on? y\n",
            "  overheating? y\n",
            "  loud fan? n\n",
            "  slow? y\n",
            "  screen flicker? n\n",
            "\n",
            "Most similar case found (similarity: 60%):\n",
            "  Problem : {'wont_turn_on': True, 'overheating': False, 'loud_fan': False, 'slow': False, 'screen_flicker': False}\n",
            "\n",
            "Suggested solution: Check the power cable and charger.\n",
            "Edit the solution? (type new solution or press Enter to keep): \n",
            "Case retained. Case base now has 5 cases.\n",
            "\n",
            "Final solution: Check the power cable and charger.\n"
          ]
        }
      ],
      "source": [
        "# Part B: Case-Based Reasoning (CBR)\n",
        "# Use case: Laptop troubleshooting assistant (same domain as the RBR program)\n",
        "\n",
        "case_base = [\n",
        "    {\"problem\": {\n",
        "        \"wont_turn_on\": True,\n",
        "        \"overheating\": False,\n",
        "        \"loud_fan\": False,\n",
        "        \"slow\": False,\n",
        "        \"screen_flicker\": False\n",
        "        },\n",
        "     \"solution\": \"Check the power cable and charger.\"\n",
        "     },\n",
        "    {\"problem\": {\n",
        "        \"wont_turn_on\": False,\n",
        "        \"overheating\": True,\n",
        "        \"loud_fan\": True,\n",
        "        \"slow\": True,\n",
        "        \"screen_flicker\": False\n",
        "        },\n",
        "     \"solution\": \"Clean the fan and vents, then use a cooling pad.\"\n",
        "     },\n",
        "    {\"problem\": {\n",
        "        \"wont_turn_on\": False,\n",
        "        \"overheating\": False,\n",
        "        \"loud_fan\": False,\n",
        "        \"slow\": True,\n",
        "        \"screen_flicker\": False\n",
        "        },\n",
        "     \"solution\": \"Free up disk space and remove startup programs.\"\n",
        "     },\n",
        "    {\"problem\": {\n",
        "        \"wont_turn_on\": False,\n",
        "        \"overheating\": False,\n",
        "        \"loud_fan\": False,\n",
        "        \"slow\": False,\n",
        "        \"screen_flicker\": True\n",
        "        },\n",
        "     \"solution\": \"Update the display driver.\"\n",
        "     },\n",
        "]\n",
        "\n",
        "FEATURES = [\n",
        "    \"wont_turn_on\",\n",
        "    \"overheating\",\n",
        "    \"loud_fan\",\n",
        "    \"slow\",\n",
        "    \"screen_flicker\"\n",
        "    ]\n",
        "\n",
        "\n",
        "# Retrieve - similarity matching\n",
        "def similarity(new_problem, old_problem):\n",
        "    # Fraction of features that have the same value (0.0 to 1.0).\n",
        "    matches = sum(1 for f in FEATURES if new_problem[f] == old_problem[f])\n",
        "    return matches / len(FEATURES)\n",
        "\n",
        "def retrieve(new_problem, case_base):\n",
        "    # Return the most similar case and its score.\n",
        "    best_case, best_score = None, -1\n",
        "    for case in case_base:\n",
        "        score = similarity(new_problem, case[\"problem\"])\n",
        "        if score > best_score:\n",
        "            best_case, best_score = case, score\n",
        "    return best_case, best_score\n",
        "\n",
        "\n",
        "# Reuse - use the solution of the most similar case\n",
        "def reuse(best_case):\n",
        "    return best_case[\"solution\"]\n",
        "\n",
        "\n",
        "# Revise - let the student adjust the solution or keep it\n",
        "def revise(solution):\n",
        "    print(f\"\\nSuggested solution: {solution}\")\n",
        "    answer = input(\"Edit the solution? (type new solution or press Enter to keep): \").strip()\n",
        "    return answer if answer else solution\n",
        "\n",
        "\n",
        "# Retain - store the new case in the case base\n",
        "def retain(new_problem, final_solution, case_base):\n",
        "    case_base.append({\"problem\": new_problem, \"solution\": final_solution})\n",
        "    print(f\"Case retained. Case base now has {len(case_base)} cases.\")\n",
        "\n",
        "\n",
        "def get_yes_no(prompt):\n",
        "    # Keep asking until the user enters a valid yes/no answer\n",
        "    while True:\n",
        "        answer = input(prompt).strip().lower()\n",
        "        if answer in [\"y\", \"yes\"]:\n",
        "            return True\n",
        "        elif answer in [\"n\", \"no\"]:\n",
        "            return False\n",
        "        else:\n",
        "            print(\"Invalid input! Please enter 'y' or 'n'.\")\n",
        "\n",
        "\n",
        "def ask_problem():\n",
        "    \"\"\"Input: ask the user yes/no questions to build the new problem.\"\"\"\n",
        "    print(\"Describe your laptop problem (y/n):\")\n",
        "    problem = {}\n",
        "    for f in FEATURES:\n",
        "        problem[f] = get_yes_no(f\"  {f.replace('_', ' ')}? \")\n",
        "    return problem\n",
        "\n",
        "def main():\n",
        "    print(\"=== Case-Based Reasoning: Laptop Troubleshooter ===\\n\")\n",
        "    new_problem = ask_problem()\n",
        "\n",
        "    best_case, score = retrieve(new_problem, case_base)\n",
        "    print(f\"\\nMost similar case found (similarity: {score:.0%}):\")\n",
        "    print(f\"  Problem : {best_case['problem']}\")\n",
        "\n",
        "    solution = reuse(best_case)\n",
        "    final_solution = revise(solution)\n",
        "    retain(new_problem, final_solution, case_base)\n",
        "\n",
        "    print(f\"\\nFinal solution: {final_solution}\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ]
    }
  ]
}